services:
  verdinho-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    networks:
      - verdinho-shared-network
    restart: unless-stopped
    container_name: verdinho-svelte

networks:
  verdinho-shared-network:
    external: true
